python3 print fix to scripts examples
Print function needs to use brackets to be compatible
both with the python2 and python3.
Without this fix following error was generated
with flags
-DKICAD_SCRIPTING_MODULES=ON
-DKICAD_SCRIPTING_PYTHON3=ON

/usr/share/kicad/demos/python_scripts_examples/gen_gerber_and_drill_files_board.py", line 95
print 'plot %s' % pctl.GetPlotFileName()
^
SyntaxError: invalid syntax

Fixes https://gitlab.com/kicad/code/kicad/-/issues/8303

Signed-off-by: Mika Laitio <lamikr@gmail.com>